# Generated by Django 3.0.4 on 2020-04-07 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parttypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dim', models.CharField(blank=True, max_length=100, null=True)),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heating.Manufacturer')),
                ('parttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heating.Parttypes')),
            ],
            options={
                'ordering': ['mpn'],
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=100, null=True)),
                ('nameandmodel', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True)),
                ('doclink', models.CharField(blank=True, max_length=200, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('fuel', models.CharField(blank=True, choices=[('EL', 'ELECTRIC'), ('AS', 'AIR SOURCE'), ('GE', 'GEOTHERMAL'), ('LP', 'LPG'), ('LC', 'LPG Combi'), ('NG', 'Natural Gas'), ('NC', 'Natural Gas Combi'), ('OI', 'OIL')], max_length=2, null=True)),
                ('parts', models.ManyToManyField(to='heating.Part')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
    ]
