# Generated by Django 3.0.4 on 2020-04-08 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0002_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliance',
            options={},
        ),
        migrations.AlterField(
            model_name='part',
            name='man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heating.Manufacturer'),
        ),
    ]
