# Generated by Django 3.0.4 on 2020-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0004_auto_20200408_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
