# Generated by Django 3.0.4 on 2020-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0005_auto_20200408_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='fuel',
            field=models.CharField(blank=True, choices=[('EL', 'ELECTRIC'), ('AS', 'AIR SOURCE'), ('GE', 'GEOTHERMAL'), ('LP', 'LPG'), ('LC', 'LPG Combi'), ('NG', 'Natural Gas'), ('NC', 'Natural Gas Combi'), ('CU', 'Combi'), ('OI', 'OIL')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='nameandmodel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='parts',
            field=models.ManyToManyField(blank=True, null=True, to='heating.Part'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
