# Generated by Django 3.0.4 on 2020-04-11 22:32

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0007_blogpost_metad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
