# Generated by Django 3.0.4 on 2020-04-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0008_auto_20200411_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='parts',
            field=models.ManyToManyField(blank=True, to='heating.Part'),
        ),
    ]
