# Generated by Django 3.0.4 on 2020-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0011_auto_20200425_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='enable_comments',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
