# Generated by Django 3.0.4 on 2020-04-26 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0012_blogpost_enable_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='enddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publishdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
