# Generated by Django 3.0.4 on 2020-04-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles2', '0002_chat_otherparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_is_visible',
            field=models.BooleanField(default=True, verbose_name='Email is verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_is_verified',
            field=models.BooleanField(default=False, verbose_name='Website is verified'),
        ),
    ]
