# Generated by Django 3.0.4 on 2020-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles2', '0003_auto_20200423_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_new_messages',
            field=models.BooleanField(default=False, verbose_name='Email notification of new messages'),
        ),
    ]
