# Generated by Django 3.0.4 on 2020-04-29 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofiles2', '0004_userprofile_notify_new_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likemodeltype', models.CharField(blank=True, max_length=1, null=True)),
                ('likemodelpk', models.PositiveIntegerField(blank=True, null=True, verbose_name='MPK')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likeowner', to=settings.AUTH_USER_MODEL, verbose_name='LikwUser')),
            ],
        ),
    ]
