# Generated by Django 3.0.4 on 2020-04-29 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofiles2', '0005_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likecomment', to='django_comments.Comment', verbose_name='LikeComment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likeuser', to=settings.AUTH_USER_MODEL, verbose_name='LikeUser')),
            ],
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
