# Generated by Django 3.0.4 on 2020-04-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles2', '0006_auto_20200429_2300'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentlikes',
            table='likeuser',
        ),
    ]
